server:
  port: 9011 #提供者的端口
spring:
  application:
    name: spring-cloud-eureka-producer

eureka:
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/
      defaultZone: http://localhost:8761/eureka/
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true