server:
  port: 9030 #提供者的端口
spring:
  application:
    name: admin-server
  security:
    user:
      name: admin
      password: admin
    boot:
      admin:
        ui:
          title: 监控管理后台
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

