server:
  port: 9001 #提供者的端口
spring:
  application:
    name: spring-cloud-consul-producer
  cloud:
    consul:
      host: lidong-consul.com
      port: 8500
      discovery:
        tags: dev
        serviceName:  spring-cloud-consul-producer   # 注册到consul的服务名称
        healthCheckPath: /actuator/health
        healthCheckInterval: 15s
        healthCheckUrl: http://127.0.0.1:9001/actuator/health
        register: true
        prefer-ip-address: false